import type { Category, Project } from './portfolioData';

/* ────────────────────────────────────────────────────────────
   Live client work — websites, landing pages, ad pages, CRM
   and AI builds currently running in production.
   ──────────────────────────────────────────────────────────── */

const palette = [
  'from-blue-700 via-indigo-700 to-purple-700',
  'from-emerald-700 via-teal-700 to-cyan-700',
  'from-orange-700 via-amber-700 to-yellow-700',
  'from-sky-700 via-blue-700 to-indigo-700',
  'from-violet-700 via-purple-700 to-fuchsia-700',
  'from-rose-700 via-pink-700 to-red-700',
  'from-teal-700 via-cyan-700 to-sky-700',
  'from-amber-700 via-orange-700 to-rose-700',
  'from-indigo-700 via-violet-700 to-purple-700',
  'from-cyan-700 via-sky-700 to-blue-700',
  'from-fuchsia-700 via-pink-700 to-rose-700',
  'from-lime-700 via-green-700 to-emerald-700',
] as const;

const stack = {
  next: ['Next.js', 'TypeScript', 'Tailwind CSS'],
  full: ['Next.js', 'TypeScript', 'Node.js', 'Tailwind CSS'],
  crm: ['Next.js', 'Node.js', 'MongoDB', 'Tailwind CSS'],
  ads: ['Next.js', 'Tailwind CSS', 'Google Ads'],
  ai: ['Next.js', 'TypeScript', 'Tailwind CSS', 'AI'],
  creative: ['Next.js', 'Framer Motion', 'Tailwind CSS'],
} as const;

interface Seed {
  slug: string;
  name: string;
  blurb: string;
  cat: Category;
  url: string;
  kind: keyof typeof stack;
  metrics: string;
  timeline: string;
  problem: string;
  solution: string;
  results: string[];
  client?: string;
  role?: string;
  quote?: string;
}

const seeds: Seed[] = [
  {
    slug: 'my-mba-admission',
    name: 'My MBA Admission',
    blurb: 'Full-stack MBA admission platform with programme discovery, eligibility checks and lead capture.',
    cat: 'Education Portals',
    url: 'https://mymbaadmission.com/',
    kind: 'full',
    metrics: 'Live in Production',
    timeline: '3 months',
    problem: 'Aspirants were navigating MBA admissions through scattered PDFs and WhatsApp forwards, with no single place to compare programmes or check eligibility.',
    solution: 'We built a structured admission platform with programme filters, eligibility logic, seat updates and a verified enquiry flow that routes straight to the counselling team.',
    results: ['Unified programme and college catalogue', 'Eligibility checker with instant results', 'Enquiry forms wired to counselling team'],
    client: 'My MBA Admission',
    role: 'Education Platform',
    quote: 'The platform turned a messy admission process into something students actually finish on their own.',
  },
  {
    slug: 'aspire-edification',
    name: 'Aspire Edification',
    blurb: 'Modern ed-tech website with course catalogue, enquiry funnels and student testimonials.',
    cat: 'Education Portals',
    url: 'https://aspireedification.com/',
    kind: 'next',
    metrics: 'Live in Production',
    timeline: '2 months',
    problem: 'The old site buried course information behind long menus and had no clear path from browsing to enquiry.',
    solution: 'We redesigned the information architecture, built a clean course catalogue and rewrote the enquiry flow so every course page ends with a single obvious next step.',
    results: ['Course catalogue with comparison views', 'Reusable enquiry flow across all programmes', 'Mobile-first layouts for student traffic'],
    client: 'Aspire Edification',
    role: 'Ed-Tech Website',
    quote: 'Cleaner, faster and finally the phone version works properly on mobile data.',
  },
  {
    slug: 'coraledu-mba',
    name: 'Coraledu — MBA',
    blurb: 'Focused MBA landing page built for admission-season ad traffic.',
    cat: 'Landing Pages',
    url: 'https://coraledu.in/mba',
    kind: 'ads',
    metrics: 'Ad Traffic Ready',
    timeline: '3 weeks',
    problem: 'Paid traffic was landing on a generic homepage with too many exit paths, so conversion stayed flat.',
    solution: 'We built a single-purpose MBA landing page with one hero promise, proof blocks and a short form — everything above the fold answers the ad visitor question.',
    results: ['Single-funnel page matched to ad copy', 'Proof and placement blocks above the fold', 'Reduced form fields for higher completion'],
    client: 'Coraledu',
    role: 'Education Group',
    quote: 'The page finally says the same thing as the ad that brought the student in.',
  },
  {
    slug: 'btech-in-bangalore',
    name: 'BTech in Bangalore',
    blurb: 'Engineering admission website covering colleges, branches and Bangalore location data.',
    cat: 'Education Portals',
    url: 'https://btechinbangalore.in/',
    kind: 'full',
    metrics: 'Live in Production',
    timeline: '2 months',
    problem: 'Students searching for BTech admission in Bangalore had no reliable page that combined college lists, branch details and location filters.',
    solution: 'We built college and branch listings with location-based filtering, detailed profiles and direct admission enquiry — all indexable for organic search.',
    results: ['Filterable college and branch database', 'SEO-friendly location landing pages', 'Direct admission enquiry on every profile'],
    client: 'BTech in Bangalore',
    role: 'Admission Portal',
    quote: 'Parents can finally compare colleges on one page instead of ten browser tabs.',
  },
  {
    slug: 'diamond-matrimonial',
    name: 'Diamond Matrimonial Services',
    blurb: 'Matrimonial services website with profile enquiry flow and lead routing.',
    cat: 'Business Websites',
    url: 'https://diamondmatrimonialservices.com/',
    kind: 'ads',
    metrics: 'Google Ads Active',
    timeline: '2 months',
    problem: 'Ad clicks were landing on a site with no clear path to connect, so leads never reached the sales team.',
    solution: 'We built a trust-first matrimonial site with service explanation, verified profile highlights and a short connect form routed directly to the team on WhatsApp and CRM.',
    results: ['Trust-led landing structure for ad traffic', 'Connect form with instant lead delivery', 'Profile highlights instead of long listings'],
    client: 'Diamond Matrimonial Services',
    role: 'Matrimonial Services',
    quote: 'Leads started arriving on the same day we launched instead of a week later.',
  },
  {
    slug: 'zabin-crm',
    name: 'Zabin CRM',
    blurb: 'Custom CRM for enquiry tracking, follow-ups and pipeline visibility.',
    cat: 'Web Apps',
    url: 'https://zabin.in/',
    kind: 'crm',
    metrics: 'Live in Production',
    timeline: '4 months',
    problem: 'The team was tracking enquiries across spreadsheets and chat threads, with no way to see which leads were actually moving.',
    solution: 'We designed and built a CRM with enquiry capture, follow-up reminders, pipeline stages and a dashboard that shows lead movement without manual updates.',
    results: ['Central enquiry pipeline with stages', 'Follow-up reminders so leads do not go cold', 'Dashboard for lead movement and volume'],
    client: 'Zabin',
    role: 'Internal CRM',
    quote: 'We stopped losing leads between forms and follow-up calls.',
  },
  {
    slug: 'mbaenroll-iibs',
    name: 'IIBS Admission',
    blurb: 'Institute-specific MBA admission landing page for campaign traffic.',
    cat: 'Landing Pages',
    url: 'https://mbaenroll.com/iibs-admission',
    kind: 'ads',
    metrics: 'Ad Traffic Ready',
    timeline: '2 weeks',
    problem: 'Institute-wise campaigns all pointed to the same generic page, so visitors could not confirm they were in the right place.',
    solution: 'We built a dedicated landing page per institute with programme-specific copy, fee and placement blocks and a direct admission form.',
    results: ['Dedicated page per institute campaign', 'Programme, fees and placements in one view', 'Form routing per campaign for attribution'],
    client: 'MBAEnroll',
    role: 'Admission Campaign',
    quote: 'Each campaign now has its own page, which made attribution far easier.',
  },
  {
    slug: 'fizzi-animated',
    name: 'Fizzi',
    blurb: 'Animated brand experience with motion-driven product storytelling.',
    cat: 'Business Websites',
    url: 'https://fizzi-animimated-project.vercel.app/',
    kind: 'creative',
    metrics: 'Live in Production',
    timeline: '1 month',
    problem: 'A static site could not convey how the product actually feels to use, so prospects judged it on screenshots alone.',
    solution: 'We built an animated experience with scroll-driven transitions and motion typography that demonstrates the product instead of describing it.',
    results: ['Scroll-driven product storytelling', 'Motion typography and transitions throughout', 'Optimised to stay smooth on mid-range phones'],
    client: 'Fizzi',
    role: 'Brand Experience',
    quote: 'People understood the product in seconds instead of reading a whole page.',
  },
  {
    slug: 'mbaenroll-ibi',
    name: 'IBI Admission',
    blurb: 'Admission landing page with programme comparison and instant enquiry.',
    cat: 'Landing Pages',
    url: 'https://mbaenroll.com/ibi',
    kind: 'ads',
    metrics: 'Ad Traffic Ready',
    timeline: '2 weeks',
    problem: 'Visitors could not compare specialisations before deciding, so most of them left without enquiring.',
    solution: 'We added a side-by-side programme comparison and moved the enquiry form into the natural decision point rather than the page footer.',
    results: ['Programme comparison table', 'Enquiry form placed at the decision point', 'Mobile-optimised for ad traffic'],
    client: 'MBAEnroll',
    role: 'Admission Campaign',
    quote: 'The comparison block alone changed how people read the page.',
  },
  {
    slug: 'beer-animation',
    name: 'Beer Animation',
    blurb: 'Creative animated microsite with playful interactions and 3D motion.',
    cat: 'Business Websites',
    url: 'https://beer-animation.vercel.app/',
    kind: 'creative',
    metrics: 'Live in Production',
    timeline: '2 weeks',
    problem: 'The client needed a launch experience that felt memorable on social sharing rather than a standard brochure page.',
    solution: 'We built a playful animated microsite with layered 3D motion, quick-load assets and share-friendly page structure for campaign traffic.',
    results: ['Playful 3D motion sequence', 'Fast first load despite heavy animation', 'Built for share-driven campaign traffic'],
    client: 'Beer Animation',
    role: 'Creative Microsite',
    quote: 'It does exactly what a launch page should — gets shared on its own.',
  },
  {
    slug: 'seven-theta-ai',
    name: 'Seven Theta',
    blurb: 'AI product landing page with capability sections and conversion flow.',
    cat: 'Landing Pages',
    url: 'https://ai-landing-page-seven-theta.vercel.app/',
    kind: 'ai',
    metrics: 'Live in Production',
    timeline: '3 weeks',
    problem: 'AI products get judged in seconds, and the previous page buried the actual capability behind marketing language.',
    solution: 'We structured the page around real capabilities, showed the output rather than the promise, and simplified the sign-up path to one screen.',
    results: ['Capability-first page structure', 'Live output previews instead of claims', 'Single-screen sign-up flow'],
    client: 'Seven Theta',
    role: 'AI Product',
    quote: 'Showing what it actually outputs removed most of the scepticism.',
  },
  {
    slug: 'mbaenroll-study-abroad',
    name: 'MBAEnroll — Study Abroad',
    blurb: 'Study abroad landing page covering destinations, eligibility and counselling.',
    cat: 'Landing Pages',
    url: 'https://mbaenroll.com/study-abroad',
    kind: 'ads',
    metrics: 'Ad Traffic Ready',
    timeline: '3 weeks',
    problem: 'Study abroad queries arrive with very different intent, and one generic page could not address any of them well.',
    solution: 'We built destination-led sections with eligibility guidance, document checklists and a counselling booking path for high-intent visitors.',
    results: ['Destination-by-destination sections', 'Document checklist to reduce drop-off', 'Counselling booking built into the flow'],
    client: 'MBAEnroll',
    role: 'Study Abroad Campaign',
    quote: 'Visitors finally get answers before they have to call us.',
  },
  {
    slug: 'mbaenroll-mbbs-abroad',
    name: 'MBAEnroll — MBBS Abroad',
    blurb: 'MBBS abroad landing page with country comparison and transparent fee structure.',
    cat: 'Landing Pages',
    url: 'https://mbaenroll.com/mbbs-abroad',
    kind: 'ads',
    metrics: 'Ad Traffic Ready',
    timeline: '3 weeks',
    problem: 'MBBS abroad decisions are high value and fee-sensitive, but the page hid the numbers until the very end.',
    solution: 'We put country-wise fees, recognition status and eligibility upfront, with a comparison layout so students can self-qualify before contacting anyone.',
    results: ['Country comparison with fees upfront', 'Recognition and eligibility clarity', 'Self-qualification flow before contact'],
    client: 'MBAEnroll',
    role: 'Medical Abroad Campaign',
    quote: 'Publishing fees on the page actually increased enquiries, not decreased them.',
  },
  {
    slug: 'mbaenroll-mba',
    name: 'MBAEnroll — MBA',
    blurb: 'Core MBA campaign page with programme tiers and fast enquiry capture.',
    cat: 'Landing Pages',
    url: 'https://mbaenroll.com/mba',
    kind: 'ads',
    metrics: 'Ad Traffic Ready',
    timeline: '2 weeks',
    problem: 'The main MBA campaign page had too much competing content and visitors dropped off before reaching the form.',
    solution: 'We cut the page down to the essentials, structured it around three programme tiers and moved the form earlier for high-intent traffic.',
    results: ['Three clear programme tiers', 'Form moved earlier in the flow', 'Page weight reduced for faster ad loads'],
    client: 'MBAEnroll',
    role: 'Core MBA Campaign',
    quote: 'Less on the page, more conversations — exactly the shift we needed.',
  },
  {
    slug: 'mbaenroll-firebird',
    name: 'Firebird',
    blurb: 'Campaign landing page with a single focused conversion goal.',
    cat: 'Landing Pages',
    url: 'https://mbaenroll.com/firebird',
    kind: 'ads',
    metrics: 'Ad Traffic Ready',
    timeline: '2 weeks',
    problem: 'Campaign pages usually get filled up over time, and this one had accumulated too many competing sections.',
    solution: 'We rebuilt it around one conversion goal, removing navigation and secondary sections so the page has a single clear path.',
    results: ['Single conversion goal per page', 'Navigation removed to avoid exits', 'Fast-loading ad landing structure'],
    client: 'MBAEnroll',
    role: 'Campaign Landing Page',
    quote: 'Removing the menu did more for conversion than any design change.',
  },
  {
    slug: 'key2education',
    name: 'Key2Education',
    blurb: 'Education consultancy website with programme guidance and counselling booking.',
    cat: 'Education Portals',
    url: 'https://key2education.com/',
    kind: 'next',
    metrics: 'Live in Production',
    timeline: '2 months',
    problem: 'The consultancy had strong offerings but no online presence that explained them or captured enquiries outside working hours.',
    solution: 'We built a clear consultancy site with programme pages, counsellor profiles and a booking flow that works without any manual follow-up.',
    results: ['Programme pages with clear guidance', 'Counsellor profiles for trust', 'Booking flow that captures off-hours enquiries'],
    client: 'Key2Education',
    role: 'Education Consultancy',
    quote: 'Enquiries now come in overnight instead of waiting for the morning.',
  },
  {
    slug: 'jp-tech',
    name: 'JP Tech',
    blurb: 'Tech services website with service breakdown and project enquiry flow.',
    cat: 'Business Websites',
    url: 'https://jp-tech.vercel.app/',
    kind: 'next',
    metrics: 'Live in Production',
    timeline: '1 month',
    problem: 'A broad tech services offering was difficult to position because nothing explained the actual specialisations.',
    solution: 'We restructured the site around specific services, added a process section and built a scoped enquiry form that captures project type up front.',
    results: ['Service-specific pages for each specialisation', 'Clear process section', 'Scoped enquiry form capturing project type'],
    client: 'JP Tech',
    role: 'Tech Services',
    quote: 'Enquiries now come in with actual project detail attached.',
  },
  {
    slug: 'theprint',
    name: 'ThePrint',
    blurb: 'Printing services website with product catalogue and quote request flow.',
    cat: 'Business Websites',
    url: 'https://theprint.in/',
    kind: 'next',
    metrics: 'Live in Production',
    timeline: '2 months',
    problem: 'Customers could not tell what the business actually printed or how to request pricing for their own job.',
    solution: 'We built a product-led website with clear categories, material and finish options and a quote request form that captures job specifics.',
    results: ['Product categories with finish options', 'Quote request capturing job specifics', 'Print-focused layouts across breakpoints'],
    client: 'ThePrint',
    role: 'Printing Services',
    quote: 'Quote requests now arrive with the details we actually need to quote.',
  },
  {
    slug: 'super-nova-ai',
    name: 'Super Nova AI',
    blurb: 'AI product website with capability walkthrough and trial sign-up.',
    cat: 'Business Websites',
    url: 'https://super-nova-ai-ruddy.vercel.app/',
    kind: 'ai',
    metrics: 'Live in Production',
    timeline: '1 month',
    problem: 'The AI offering was described in abstract terms, so visitors could not tell whether it solved their problem.',
    solution: 'We rebuilt the site around a capability walkthrough that shows the product working, with a trial path that skips the long sales cycle.',
    results: ['Capability walkthrough with live output', 'Direct trial sign-up without sales call', 'Clear technical positioning'],
    client: 'Super Nova AI',
    role: 'AI Product',
    quote: 'The walkthrough section does the selling for us now.',
  },
  {
    slug: 'abroadstudy4u-russia',
    name: 'MBBS in Russia',
    blurb: 'Russia MBBS ad landing page with fees, eligibility and seat guidance.',
    cat: 'Landing Pages',
    url: 'https://abroadstudy4u.com/mbbs-in-russia',
    kind: 'ads',
    metrics: 'Google Ads Active',
    timeline: '2 weeks',
    problem: 'Russia-specific ad traffic was hitting a shared page, so eligibility and fee questions were answered only after contact.',
    solution: 'We built a Russia-specific page with upfront fees, seat availability and eligibility guidance so visitors can self-assess immediately.',
    results: ['Country-specific fees and seats', 'Eligibility self-assessment', 'Ad copy matched to page content'],
    client: 'AbroadStudy4u',
    role: 'Medical Abroad',
    quote: 'Answering eligibility on the page cut down the back-and-forth calls.',
  },
  {
    slug: 'abroadstudy4u-india',
    name: 'MBBS in India',
    blurb: 'India MBBS ad page covering domestic college options and admission route.',
    cat: 'Landing Pages',
    url: 'https://abroadstudy4u.com/mbbs-in-india',
    kind: 'ads',
    metrics: 'Google Ads Active',
    timeline: '2 weeks',
    problem: 'Domestic MBBS queries were being sent to the same flow as abroad candidates, which did not match their intent at all.',
    solution: 'We built a separate India-focused page covering domestic college routes, exam structure and admission steps with its own enquiry path.',
    results: ['India-specific admission route', 'Exam structure explained upfront', 'Separate enquiry path for domestic intent'],
    client: 'AbroadStudy4u',
    role: 'Medical Education',
    quote: 'Splitting domestic and abroad queries doubled the quality of enquiries.',
  },
  {
    slug: 'abroadstudy4u-georgia',
    name: 'MBBS in Georgia',
    blurb: 'Georgia MBBS ad landing page with hostel, fees and recognition details.',
    cat: 'Landing Pages',
    url: 'https://abroadstudy4u.com/mbbs-in-georgia',
    kind: 'ads',
    metrics: 'Google Ads Active',
    timeline: '2 weeks',
    problem: 'Georgia enquiries were dominated by practical questions about living costs that the page did not answer.',
    solution: 'We added hostel and living cost breakdowns alongside fees and recognition status, so students get the full picture before enquiring.',
    results: ['Hostel and living cost breakdown', 'Recognition status stated clearly', 'Complete fee picture before contact'],
    client: 'AbroadStudy4u',
    role: 'Medical Abroad',
    quote: 'Answering the hostel question on the page removed most objections.',
  },
  {
    slug: 'abroadstudy4u-kyrgyzstan',
    name: 'MBBS in Kyrgyzstan',
    blurb: 'Kyrgyzstan MBBS ad page with budget breakdown and admission steps.',
    cat: 'Landing Pages',
    url: 'https://abroadstudy4u.com/mbbs-in-kyrgyzstan',
    kind: 'ads',
    metrics: 'Google Ads Active',
    timeline: '2 weeks',
    problem: 'Budget-conscious candidates needed a full cost picture, and the shared landing page only showed headline fees.',
    solution: 'We built a Kyrgyzstan page with a complete budget breakdown including travel and stay, plus a clear step-by-step admission flow.',
    results: ['Full budget breakdown beyond headline fees', 'Step-by-step admission flow', 'Designed for cost-first research'],
    client: 'AbroadStudy4u',
    role: 'Medical Abroad',
    quote: 'The full cost breakdown made students trust the numbers.',
  },
  {
    slug: 'mbbs-india-neet',
    name: 'MBBS India NEET',
    blurb: 'NEET-focused landing page for admission counselling and guidance.',
    cat: 'Landing Pages',
    url: 'https://mbbsindianeet.com/',
    kind: 'ads',
    metrics: 'Ad Traffic Ready',
    timeline: '2 weeks',
    problem: 'NEET candidates needed rank-based counselling more than general college information, and the page mixed both equally.',
    solution: 'We built a NEET-specific page centred on rank counselling, college prediction and next-step guidance after results.',
    results: ['Rank-based counselling focus', 'College prediction after results', 'Post-result next-step guidance'],
    client: 'AbroadStudy4u',
    role: 'NEET Counselling',
    quote: 'Rank-first structure matched exactly what students search for.',
  },
  {
    slug: 'your-online-mba',
    name: 'Your Online MBA',
    blurb: 'Online MBA marketing site with programme tiers and comparison.',
    cat: 'Business Websites',
    url: 'https://youronlinemba.in/',
    kind: 'next',
    metrics: 'Live in Production',
    timeline: '2 months',
    problem: 'Online MBA prospects were comparing programmes across multiple sites with no consistent information to compare against.',
    solution: 'We built a single site with standardised programme pages, a side-by-side comparison and clear mode-of-study differences.',
    results: ['Standardised programme pages', 'Side-by-side comparison tool', 'Clear online vs classroom differentiation'],
    client: 'Your Online MBA',
    role: 'Education Platform',
    quote: 'Comparison on one page changed how people shortlist.',
  },
  {
    slug: 'summit-global',
    name: 'Summit Global',
    blurb: 'Corporate website with service lines and enquiry routing.',
    cat: 'Business Websites',
    url: 'https://summitglobal.co.in/',
    kind: 'next',
    metrics: 'Live in Production',
    timeline: '2 months',
    problem: 'A broad corporate offering was hard to navigate and enquiries arrived without any indication of what the visitor needed.',
    solution: 'We restructured the site around distinct service lines and built an enquiry form that routes each submission to the right team.',
    results: ['Service-line based site structure', 'Enquiry routing by service need', 'Consistent corporate presentation'],
    client: 'Summit Global',
    role: 'Corporate Services',
    quote: 'Enquiries land with the right team now instead of a shared inbox.',
  },
  {
    slug: 'summit-foundation',
    name: 'Summit Foundation',
    blurb: 'Foundation website with initiatives, impact sections and volunteering.',
    cat: 'Business Websites',
    url: 'https://summitfoundationglobal.com/',
    kind: 'next',
    metrics: 'Live in Production',
    timeline: '2 months',
    problem: 'The foundation needed to present its work and impact clearly to donors and partners, which the previous site did not achieve.',
    solution: 'We built an impact-focused site with initiative pages, measurable outcomes and separate paths for donors, partners and volunteers.',
    results: ['Initiative pages with clear outcomes', 'Donor, partner and volunteer paths', 'Impact presented with concrete numbers'],
    client: 'Summit Foundation',
    role: 'NGO / Foundation',
    quote: 'Partners finally understood our work without a meeting first.',
  },
  {
    slug: 'coffee-bilingual',
    name: 'Bilingual Coffee Website',
    blurb: 'Bilingual coffee brand site with language toggle and localised content.',
    cat: 'Business Websites',
    url: 'https://coffee-on-bilingual-website.vercel.app/',
    kind: 'next',
    metrics: 'Live in Production',
    timeline: '1 month',
    problem: 'Serving two audiences from one site meant duplicated pages and inconsistent branding between language versions.',
    solution: 'We built a single bilingual site with a proper language toggle, parallel content structure and shared brand styling across both languages.',
    results: ['Single site serving two languages', 'Parallel content structure with shared branding', 'No duplicate URLs for search engines'],
    client: 'Coffee Brand',
    role: 'Brand Website',
    quote: 'One site, two languages, consistent brand — exactly what we needed.',
  },
  {
    slug: 'real-estate-theme',
    name: 'Real Estate Theme',
    blurb: 'Property listing website with map search, filters and listing detail pages.',
    cat: 'Web Apps',
    url: 'https://real-eastate-theme-1.vercel.app/?theme=template-1',
    kind: 'full',
    metrics: 'Live in Production',
    timeline: '1 month',
    problem: 'Property searches needed location and budget filters, but a flat listing page forced visitors to scan everything manually.',
    solution: 'We built a listing experience with combined location, price and property-type filters, plus detail pages with galleries and enquiry actions.',
    results: ['Combined location, price and type filters', 'Property detail pages with galleries', 'Enquiry action on every listing'],
    client: 'Real Estate Client',
    role: 'Property Platform',
    quote: 'Filtering changed the site from a brochure into something usable.',
  },
  {
    slug: 'css-founder',
    name: 'CSS Founder',
    blurb: 'Founder portfolio site with project storytelling and contact flow.',
    cat: 'Business Websites',
    url: 'https://cssfounder.com/',
    kind: 'next',
    metrics: 'Live in Production',
    timeline: '1 month',
    problem: 'The founder needed a personal site that led to enquiries rather than just listing past work.',
    solution: 'We built a narrative-first portfolio where each project explains the decision behind it, ending in a direct contact path.',
    results: ['Project storytelling with decision context', 'Direct contact path from every project', 'Personal brand focused layout'],
    client: 'CSS Founder',
    role: 'Personal Brand',
    quote: 'Visitors read the projects properly instead of just skimming.',
  },
  {
    slug: 'dream-medicine',
    name: 'Dream Medicine',
    blurb: 'Medical education ad site with programme pages and counselling capture.',
    cat: 'Education Portals',
    url: 'https://dreammedicine.org/',
    kind: 'ads',
    metrics: 'Google Ads Active',
    timeline: '2 months',
    problem: 'Paid medical-education traffic landed on a page with too many competing calls to action.',
    solution: 'We rebuilt the site around programme discovery and counselling capture, with one primary action per page.',
    results: ['Programme discovery structure', 'Single primary action per page', 'Built for Google Ads traffic'],
    client: 'Dream Medicine',
    role: 'Medical Education',
    quote: 'One action per page cleaned up the whole conversion flow.',
  },
  {
    slug: 'lexicon-mile',
    name: 'Lexicon Mile',
    blurb: 'Ad-optimised business site with service pages and lead capture.',
    cat: 'Business Websites',
    url: 'https://lexiconmile.com/',
    kind: 'ads',
    metrics: 'Google Ads Active',
    timeline: '2 months',
    problem: 'Existing ad spend was sending visitors to pages that did not reflect the ad promise, hurting both conversion and quality score.',
    solution: 'We rebuilt the landing experience so ad intent, page content and the form question all match, with dedicated pages per service.',
    results: ['Ad intent matched to page content', 'Dedicated page per service', 'Cleaner lead capture flow'],
    client: 'Lexicon Mile',
    role: 'Business Services',
    quote: 'Matching page to ad improved both leads and cost per lead.',
  },
  {
    slug: 'the-medical-admission',
    name: 'The Medical Admission',
    blurb: 'Medical admission guidance site with exam and college planning tools.',
    cat: 'Education Portals',
    url: 'https://themedicaladmission.in/',
    kind: 'ads',
    metrics: 'Google Ads Active',
    timeline: '2 months',
    problem: 'Students needed exam planning and college shortlisting together, and the site only supported one or the other.',
    solution: 'We built combined exam guidance and college discovery with planning tools that connect both into one admission journey.',
    results: ['Exam guidance and college discovery combined', 'Planning tools connecting both steps', 'Ad-ready entry pages per intent'],
    client: 'The Medical Admission',
    role: 'Admission Guidance',
    quote: 'Students finally have one place for the whole admission plan.',
  },
  {
    slug: 'faraz-portfolio',
    name: 'Faraz',
    blurb: 'Personal portfolio site with project case studies and contact section.',
    cat: 'Business Websites',
    url: 'https://faraz.site/',
    kind: 'creative',
    metrics: 'Live in Production',
    timeline: '3 weeks',
    problem: 'The portfolio needed to demonstrate range across projects rather than look like a single-discipline resume.',
    solution: 'We built a project-led portfolio where each case study carries its own visual treatment, keeping the site cohesive without looking repetitive.',
    results: ['Distinct visual treatment per project', 'Cohesive layout across varied work', 'Clear contact path at the end'],
    client: 'Faraz',
    role: 'Personal Portfolio',
    quote: 'Every project looks different but the site still feels like one brand.',
  },
  {
    slug: 'sumit-negi-portfolio',
    name: 'Sumit Negi',
    blurb: 'Personal developer portfolio with live project links and skills overview.',
    cat: 'Business Websites',
    url: 'https://thesumitnegi.site/',
    kind: 'next',
    metrics: 'Live in Production',
    timeline: '2 weeks',
    problem: 'A developer portfolio needs to prove capability with working links, not just describe it.',
    solution: 'We built a portfolio where every project links to something live, with a skills section and a direct hiring-oriented contact path.',
    results: ['Every project links to a live build', 'Skills and stack presented clearly', 'Contact path aimed at hiring conversations'],
    client: 'Sumit Negi',
    role: 'Personal Portfolio',
    quote: 'Live links made the difference straight away.',
  },
  {
    slug: 'himalayan-education',
    name: 'Himalayan Education',
    blurb: 'Education consultancy website with programme guidance and counselling.',
    cat: 'Education Portals',
    url: 'https://himalayaneducation.com/',
    kind: 'next',
    metrics: 'Live in Production',
    timeline: '2 months',
    problem: 'Students needed clarity on which programme suited them before committing to a counselling call.',
    solution: 'We built programme pages with clear eligibility and outcomes, plus a guidance questionnaire that routes students to the right counsellor.',
    results: ['Clear eligibility and outcomes per programme', 'Guidance questionnaire for routing', 'Counsellor matching built in'],
    client: 'Himalayan Education',
    role: 'Education Consultancy',
    quote: 'The questionnaire routes students to the right counsellor automatically.',
  },
  {
    slug: 'ad2print',
    name: 'AD2Print',
    blurb: 'Online printing services website with instant quote and order flow.',
    cat: 'Business Websites',
    url: 'https://ad2print.in/',
    kind: 'full',
    metrics: 'Live in Production',
    timeline: '2 months',
    problem: 'Customers had to call for every quote, which was slow for them and expensive for the business.',
    solution: 'We built a self-serve quote flow where customers choose product, size, quantity and finish and get pricing without waiting for a call.',
    results: ['Self-serve instant quote flow', 'Product, size and finish configuration', 'Order path without phone dependency'],
    client: 'AD2Print',
    role: 'Printing Services',
    quote: 'Quotes now happen instantly instead of waiting on a call.',
  },
  {
    slug: 'anita-printers',
    name: 'Anita Printers',
    blurb: 'Print business website with product range showcase and contact.',
    cat: 'Business Websites',
    url: 'https://anitaprinters.in/',
    kind: 'next',
    metrics: 'Live in Production',
    timeline: '1 month',
    problem: 'A wide product range was presented as a single undifferentiated list, making it hard to find anything.',
    solution: 'We rebuilt the catalogue into clear categories with filters, and added a contact flow that pre-fills the product enquiry.',
    results: ['Categorised, filterable product range', 'Contact flow pre-filled with product context', 'Mobile-friendly browsing'],
    client: 'Anita Printers',
    role: 'Printing Services',
    quote: 'Customers can actually find what they need now.',
  },
  {
    slug: 'negicaterer',
    name: 'Negicaterer',
    blurb: 'Catering services website with menu browsing and booking enquiry.',
    cat: 'Business Websites',
    url: 'https://negicaterer.in/',
    kind: 'next',
    metrics: 'Live in Production',
    timeline: '1 month',
    problem: 'Menus were buried in PDFs, so most visitors never saw what was actually on offer.',
    solution: 'We built browsable menu sections with clear pricing and a booking enquiry flow that captures event details.',
    results: ['Browsable menu sections with pricing', 'Booking enquiry capturing event details', 'Mobile-first browsing for local traffic'],
    client: 'Negicaterer',
    role: 'Catering Services',
    quote: 'Menus being online brought in far better enquiries.',
  },
  {
    slug: 'apply-mbbs',
    name: 'Apply MBBS',
    blurb: 'MBBS application portal with country options and guided application.',
    cat: 'Education Portals',
    url: 'https://applymbbs.in/',
    kind: 'full',
    metrics: 'Live in Production',
    timeline: '2 months',
    problem: 'Applying to MBBS abroad meant collecting information from multiple sources with no single starting point.',
    solution: 'We built a guided application portal where students pick a destination, see requirements and complete the application in one flow.',
    results: ['Destination-based application flow', 'Requirements shown before applying', 'Single guided application journey'],
    client: 'Apply MBBS',
    role: 'Application Portal',
    quote: 'Students complete an application without needing a call.',
  },
  {
    slug: 'abroadstudy4u-us-bangla',
    name: 'MBBS — USA & Bangladesh',
    blurb: 'Combined USA and Bangladesh MBBS ad landing page.',
    cat: 'Landing Pages',
    url: 'https://abroadstudy4u.com/us-bangla',
    kind: 'ads',
    metrics: 'Ad Traffic Ready',
    timeline: '2 weeks',
    problem: 'One ad campaign covered two very different destinations, so neither had enough detail to answer real questions.',
    solution: 'We built a combined page with clearly separated destination sections, letting each market see relevant detail without splitting the campaign.',
    results: ['Separated destination sections in one page', 'Market-relevant detail for both audiences', 'Single page serving one campaign'],
    client: 'AbroadStudy4u',
    role: 'Medical Abroad',
    quote: 'Splitting sections inside one page kept the campaign simple.',
  },
  {
    slug: 'abroadstudy4u-international',
    name: 'International College',
    blurb: 'International college listing landing page for admission enquiries.',
    cat: 'Landing Pages',
    url: 'https://abroadstudy4u.com/international-college',
    kind: 'ads',
    metrics: 'Ad Traffic Ready',
    timeline: '2 weeks',
    problem: 'International college queries needed institution detail that the general study-abroad page did not provide.',
    solution: 'We built a dedicated international college page with institution profiles, course details and a focused admission enquiry.',
    results: ['Institution profiles with course detail', 'Focused international admission enquiry', 'Dedicated page for college intent'],
    client: 'AbroadStudy4u',
    role: 'International Admissions',
    quote: 'College-specific questions now get college-specific answers.',
  },
  {
    slug: 'abroadstudy4u-zh-college',
    name: 'ZH College',
    blurb: 'Single-institution MBBS landing page with seat and fee details.',
    cat: 'Landing Pages',
    url: 'https://abroadstudy4u.com/zh-college',
    kind: 'ads',
    metrics: 'Ad Traffic Ready',
    timeline: '2 weeks',
    problem: 'A single-institution campaign was sharing a generic page, so seats and fee specifics were not communicated.',
    solution: 'We built a dedicated institution page with seat availability, fee structure, eligibility and a direct admission form.',
    results: ['Seat availability shown on page', 'Fee structure and eligibility upfront', 'Direct admission form for the institution'],
    client: 'AbroadStudy4u',
    role: 'Institutional Campaign',
    quote: 'A page for just this college converted much better.',
  },
];

/**
 * Slugs with a verified live screenshot in `public/images/projects/*.png`.
 * Anything missing from this list (blocked by a bot-wall, 404, or an
 * unreachable host) falls back to the generated SVG mockup instead — a broken
 * or misleading screenshot in a portfolio is worse than a clean placeholder.
 */
const screenshotted = new Set([
  'my-mba-admission',
  'aspire-edification',
  'coraledu-mba',
  'btech-in-bangalore',
  'mbaenroll-iibs',
  'mbaenroll-ibi',
  'beer-animation',
  'seven-theta-ai',
  'mbaenroll-study-abroad',
  'mbaenroll-mbbs-abroad',
  'key2education',
  'jp-tech',
  'theprint',
  'abroadstudy4u-russia',
  'abroadstudy4u-india',
  'abroadstudy4u-georgia',
  'abroadstudy4u-kyrgyzstan',
  'mbbs-india-neet',
  'summit-global',
  'summit-foundation',
  'coffee-bilingual',
  'real-estate-theme',
  'css-founder',
  'dream-medicine',
  'lexicon-mile',
  'the-medical-admission',
  'ad2print',
  'anita-printers',
  'negicaterer',
  'apply-mbbs',
  'abroadstudy4u-us-bangla',
  'abroadstudy4u-international',
  'abroadstudy4u-zh-college',
]);

const build = (seed: Seed, i: number): Project => ({
  id: seed.slug,
  title: `${seed.name} — ${seed.blurb.split('.')[0]}`,
  description: seed.blurb,
  category: seed.cat,
  image: screenshotted.has(seed.slug)
    ? `/images/projects/${seed.slug}.webp`
    : `/images/projects/${seed.slug}.svg`,
  imageAlt: `${seed.name} website preview`,
  gradient: palette[i % palette.length],
  tech: [...stack[seed.kind]],
  metrics: seed.metrics,
  demoUrl: seed.url,
  overview: `${seed.blurb} ${seed.solution}`,
  problem: seed.problem,
  solution: seed.solution,
  technologies: [...stack[seed.kind]],
  timeline: seed.timeline,
  results: seed.results,
  testimonial: {
    quote: seed.quote ?? 'Delivered end to end by Weblign — strategy, design and build.',
    name: seed.client ?? seed.name,
    role: seed.role ?? 'Client',
  },
});

export const additionalProjects: Project[] = seeds.map(build);